//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaKi.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChaKi.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   CREATE INDEX bunsetsu_index ON bunsetsu (sentence_id) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexBunsetsuStatement {
            get {
                return ResourceManager.GetString("CreateIndexBunsetsuStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX cform_ctype_index ON cform_ctype (cform_id, ctype_id) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexCFormCTypeStatement {
            get {
                return ResourceManager.GetString("CreateIndexCFormCTypeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX cform_index ON cform (cform) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexCFormStatement {
            get {
                return ResourceManager.GetString("CreateIndexCFormStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexCorpusAttributeStatement {
            get {
                return ResourceManager.GetString("CreateIndexCorpusAttributeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX ctype_index ON ctype (ctype) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexCTypeStatement {
            get {
                return ResourceManager.GetString("CreateIndexCTypeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX group_attribute_group_index ON group_attribute (group_id) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexGroupAttributeGroupStatement {
            get {
                return ResourceManager.GetString("CreateIndexGroupAttributeGroupStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX group_member_group_index ON group_member ( group_id ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexGroupMemberStatement1 {
            get {
                return ResourceManager.GetString("CreateIndexGroupMemberStatement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX group_member_member_index ON group_member ( member_id ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexGroupMemberStatement2 {
            get {
                return ResourceManager.GetString("CreateIndexGroupMemberStatement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexGroupStatement {
            get {
                return ResourceManager.GetString("CreateIndexGroupStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX lexeme_surface_index ON lexeme (surface) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexLexemeStatement1 {
            get {
                return ResourceManager.GetString("CreateIndexLexemeStatement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX lexeme_reading_index ON lexeme (reading) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexLexemeStatement2 {
            get {
                return ResourceManager.GetString("CreateIndexLexemeStatement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX lexeme_pronunciation_index ON lexeme (pronunciation) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexLexemeStatement3 {
            get {
                return ResourceManager.GetString("CreateIndexLexemeStatement3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX lexeme_base_lexeme_index ON lexeme (base_lexeme_ref) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexLexemeStatement4 {
            get {
                return ResourceManager.GetString("CreateIndexLexemeStatement4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX lexeme_part_of_speech_index ON lexeme (part_of_speech_id) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexLexemeStatement5 {
            get {
                return ResourceManager.GetString("CreateIndexLexemeStatement5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX lexemes_ctype_index ON lexeme (ctype_id) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexLexemeStatement6 {
            get {
                return ResourceManager.GetString("CreateIndexLexemeStatement6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX lexeme_cform_index ON lexeme (cform_id) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexLexemeStatement7 {
            get {
                return ResourceManager.GetString("CreateIndexLexemeStatement7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX link_attribute_link_index ON link_attribute (link_id,attribute_key) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexLinkAttributeLinkStatement {
            get {
                return ResourceManager.GetString("CreateIndexLinkAttributeLinkStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX link_from_segment_index ON link (from_segment_id) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexLinkStatement1 {
            get {
                return ResourceManager.GetString("CreateIndexLinkStatement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX link_to_segment_index ON link (to_segment_id ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexLinkStatement2 {
            get {
                return ResourceManager.GetString("CreateIndexLinkStatement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX link_from_sentence_index ON link (from_sentence_id ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexLinkStatement3 {
            get {
                return ResourceManager.GetString("CreateIndexLinkStatement3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX link_to_sentence_index ON link (to_sentence_id ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexLinkStatement4 {
            get {
                return ResourceManager.GetString("CreateIndexLinkStatement4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX part_of_speech_index ON part_of_speech (part_of_speech) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexPartOfSpeechStatement {
            get {
                return ResourceManager.GetString("CreateIndexPartOfSpeechStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX segment_attribute_segment_index ON segment_attribute (segment_id) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexSegmentAttributeSegmentStatement {
            get {
                return ResourceManager.GetString("CreateIndexSegmentAttributeSegmentStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX segment_end_char_index ON segment (end_char) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexSegmentsStatement2 {
            get {
                return ResourceManager.GetString("CreateIndexSegmentsStatement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX segment_start_char_index ON segment (start_char) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexSegmentStatement1 {
            get {
                return ResourceManager.GetString("CreateIndexSegmentStatement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX segment_sentence_index ON segment (sentence_id) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexSegmentStatement3 {
            get {
                return ResourceManager.GetString("CreateIndexSegmentStatement3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX sentence_documenttag_index ON sentence_documenttag(sentence_id); に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexSentenceDocumenttagStatement1 {
            get {
                return ResourceManager.GetString("CreateIndexSentenceDocumenttagStatement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX sentence_start_char_index ON sentence (start_char) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexSentenceStatement1 {
            get {
                return ResourceManager.GetString("CreateIndexSentenceStatement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX sentence_end_char_index ON sentence (end_char) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexSentenceStatement2 {
            get {
                return ResourceManager.GetString("CreateIndexSentenceStatement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX word_sentence_id_index ON word (sentence_id ASC) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexWordStatement1 {
            get {
                return ResourceManager.GetString("CreateIndexWordStatement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX word_lexeme_id_index ON word (lexeme_id ASC) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexWordStatement2 {
            get {
                return ResourceManager.GetString("CreateIndexWordStatement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX word_bunsetsu_segment_id_index ON word (bunsetsu_segment_id  ASC) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexWordStatement3 {
            get {
                return ResourceManager.GetString("CreateIndexWordStatement3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX word_start_time_index ON word (start_time) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexWordStatement4 {
            get {
                return ResourceManager.GetString("CreateIndexWordStatement4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX word_end_time_index ON word (end_time) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexWordStatement5 {
            get {
                return ResourceManager.GetString("CreateIndexWordStatement5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX word_duration_index ON word (duration) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexWordStatement6 {
            get {
                return ResourceManager.GetString("CreateIndexWordStatement6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE INDEX word_word_index ON word_word (from_word) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateIndexWordWordStatement {
            get {
                return ResourceManager.GetString("CreateIndexWordWordStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE attribute_constraint (
        ///  id int primary key,
        ///  tag_definition_id int not null,
        ///  attribute_key varchar(255) not null,
        ///  mandatory bool,
        ///  value_type varchar(255) not null,
        ///  value_candidates varchar(255),
        ///  default_value varchar(255),
        ///  description text,
        ///  version_id int not null
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableAttributeConstraintStatement {
            get {
                return ResourceManager.GetString("CreateTableAttributeConstraintStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE bunsetsu (
        /// id int primary key,
        /// position int,
        /// sentence_id int,
        /// dep_bunsetsu_id int,
        /// dep_relation varchar(16)
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableBunsetsuStatement {
            get {
                return ResourceManager.GetString("CreateTableBunsetsuStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE cform_ctype (
        /// cform_id int,
        /// ctype_id int) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableCFormCTypeStatement {
            get {
                return ResourceManager.GetString("CreateTableCFormCTypeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE cform (
        /// id int primary key,
        /// cform varchar(255)
        /// ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableCFormStatement {
            get {
                return ResourceManager.GetString("CreateTableCFormStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE corpus_attribute (
        /// id int primary key,
        /// name varchar(255),
        /// value varchar(255)
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableCorpusAttributeStatement {
            get {
                return ResourceManager.GetString("CreateTableCorpusAttributeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE ctype (
        /// id int primary key,
        /// name1 varchar(255),
        /// name2 varchar(255),
        /// ctype varchar(255)
        /// ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableCTypeStatement {
            get {
                return ResourceManager.GetString("CreateTableCTypeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE document_set_document (
        ///  document_id int not null,
        ///  document_set_id int not null
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableDocumentSetDocumentStatement {
            get {
                return ResourceManager.GetString("CreateTableDocumentSetDocumentStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE document_set_project (
        ///  document_set_project_id int primary key,
        ///  document_set_id int not null,
        ///  project_id int not null
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableDocumentSetProjectStatement {
            get {
                return ResourceManager.GetString("CreateTableDocumentSetProjectStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE document_set_project_user (
        ///  document_set_project_id int not null,
        ///  user_id int not null,
        ///  user_privilege int not null
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableDocumentSetProjectUserStatement {
            get {
                return ResourceManager.GetString("CreateTableDocumentSetProjectUserStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE document_set (
        ///  document_set_id  int primary key,
        ///  document_set_name varchar(255),
        ///  comments text
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableDocumentsetStatement {
            get {
                return ResourceManager.GetString("CreateTableDocumentsetStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE document_set_user (
        ///  user_id int not null,
        ///  document_set_id int not null,
        ///  user_privilege int
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableDocumentSetUserStatement {
            get {
                return ResourceManager.GetString("CreateTableDocumentSetUserStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE document (
        ///  document_id  int primary key,
        ///  document_order int,
        ///  filename varchar(255),
        ///  document_text longtext
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableDocumentStatement {
            get {
                return ResourceManager.GetString("CreateTableDocumentStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE documenttag (
        ///  id             int primary key,
        ///  tag           varchar(255),
        ///  description text,
        ///  document_id int not null,
        ///  updated_at timestamp
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableDocumentTagStatement {
            get {
                return ResourceManager.GetString("CreateTableDocumentTagStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE group_attribute (
        /// id bigint primary key,
        /// group_id bigint not null,
        /// attribute_key varchar(255) not null,
        /// attribute_value varchar(255) not null,
        /// version_id int not null,
        /// project_id int not null,
        /// user_id int,
        /// createtime timestamp not null default CURRENT_TIMESTAMP,
        /// comments text
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableGroupAttributeStatement {
            get {
                return ResourceManager.GetString("CreateTableGroupAttributeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE group_constraint (
        ///  id int primary key,
        ///  tag_definition_id int not null,
        ///  element_tag_definition_id int not null,
        ///  element_segment_condition varchar(255),
        ///  description text,
        ///  version_id int not null
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableGroupConstraintStatement {
            get {
                return ResourceManager.GetString("CreateTableGroupConstraintStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE group_member (
        /// group_id bigint not null,
        /// object_type varchar(8) not null default &quot;Segment&quot;,
        /// member_id bigint not null,
        /// project_id int,
        /// user_id int,
        /// createtime timestamp not null default CURRENT_TIMESTAMP
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableGroupMemberStatement {
            get {
                return ResourceManager.GetString("CreateTableGroupMemberStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE group_element (
        /// id bigint primary key,
        /// tag_definition_id int not null,
        /// version_id int not null,
        /// project_id int not null,
        /// user_id int,
        /// createtime timestamp not null default CURRENT_TIMESTAMP,
        /// comments text
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableGroupStatement {
            get {
                return ResourceManager.GetString("CreateTableGroupStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE lexeme (
        ///  id                 int primary key,
        ///  surface         varchar(255),
        ///  reading         varchar(255) default &apos;&apos;,
        ///  lemmaform   varchar(255) default &apos;&apos;,
        ///  pronunciation  varchar(255) default &apos;&apos;,
        ///  base_lexeme_ref   int not null,
        ///  lemma        varchar(255) default &apos;&apos;,
        ///  part_of_speech_id  int not null,
        ///  ctype_id       int not null,
        ///  cform_id       int not null,
        ///  updated_at    timestamp,
        ///  frequency      int default 0,
        ///  custom          text
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableLexemeStatement {
            get {
                return ResourceManager.GetString("CreateTableLexemeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE link_attribute (
        /// id bigint primary key,
        /// link_id bigint not null,
        /// attribute_key varchar(255) not null,
        /// attribute_value varchar(255) not null,
        /// version_id int not null,
        /// project_id int not null,
        /// user_id int,
        /// createtime timestamp not null default CURRENT_TIMESTAMP,
        /// comments text
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableLinkAttributeStatement {
            get {
                return ResourceManager.GetString("CreateTableLinkAttributeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE link_constraint (
        ///  id int primary key,
        ///  tag_definition_id int not null,
        ///  from_tag_definition_id int not null,
        ///  from_segment_condition varchar(255),
        ///  to_tag_definition_id int not null,
        ///  to_segment_condition varchar(255),
        ///  description text,
        ///  version_id int not null
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableLinkConstraintStatement {
            get {
                return ResourceManager.GetString("CreateTableLinkConstraintStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE link (
        /// id bigint primary key,
        /// tag_definition_id int not null,
        /// version_id int not null,
        /// from_segment_id bigint not null,
        /// to_segment_id bigint not null,
        /// project_id int not null,
        /// user_id int,
        /// createtime timestamp not null default CURRENT_TIMESTAMP,
        /// comments text,
        /// from_sentence_id int,
        /// to_sentence_id int,
        /// lexeme_id int
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableLinkStatement {
            get {
                return ResourceManager.GetString("CreateTableLinkStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE part_of_speech (
        /// id int primary key,
        /// name1 varchar(255),
        /// name2 varchar(255),
        /// name3 varchar(255),
        /// name4 varchar(255),
        /// part_of_speech varchar(255)
        /// ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTablePartOfSpeechStatement {
            get {
                return ResourceManager.GetString("CreateTablePartOfSpeechStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE project (
        ///  project_id  int primary key,
        ///  comments text,
        ///  document_privilege smallint,
        ///  tagset_privilege smallint
        ///)
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableProjectStatement {
            get {
                return ResourceManager.GetString("CreateTableProjectStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE project_tagset (
        ///  project_id  int not null,
        ///  tagset_id int not null,
        ///  tagset_role int
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableProjectTagsetStatement {
            get {
                return ResourceManager.GetString("CreateTableProjectTagsetStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE project_user (
        ///  user_id  int not null,
        ///  project_id int not null,
        ///  user_privilege int
        ///)
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableProjectUserStatement {
            get {
                return ResourceManager.GetString("CreateTableProjectUserStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE segment_attribute (
        /// id bigint primary key,
        /// segment_id bigint not null,
        /// attribute_key varchar(255) not null,
        /// attribute_value varchar(255) not null,
        /// version_id int not null,
        /// project_id int not null,
        /// user_id int,
        /// createtime timestamp not null default CURRENT_TIMESTAMP,
        /// comments text
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableSegmentAttributeStatement {
            get {
                return ResourceManager.GetString("CreateTableSegmentAttributeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE segment_constraint (
        ///  id int primary key,
        ///  tag_definition_id int not null,
        ///  base_tag_definition_id int not null,
        ///  base_segment_condition varchar(255),
        ///  description text,
        ///  version_id int not null
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableSegmentConstraintStatement {
            get {
                return ResourceManager.GetString("CreateTableSegmentConstraintStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE segment (
        /// id bigint primary key,
        /// tag_definition_id int not null,
        /// version_id int not null,
        /// document_id int not null,
        /// start_char int not null,
        /// end_char int not null,
        /// string_value text not null,
        /// project_id int not null,
        /// user_id int not null,
        /// createtime timestamp not null default CURRENT_TIMESTAMP,
        /// comments text,
        /// sentence_id int,
        /// lexeme_id int
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableSegmentStatement {
            get {
                return ResourceManager.GetString("CreateTableSegmentStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE sentence_documenttag (
        ///  sentence_id int not null,
        ///  documenttag_id int not null
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableSentenceDocumentTagStatement {
            get {
                return ResourceManager.GetString("CreateTableSentenceDocumentTagStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE sentence (
        ///  id             int primary key,
        ///  start_char    int not null,
        ///  end_char     int not null,
        ///  document_id int not null,
        ///  pos           int not null
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableSentenceStatement {
            get {
                return ResourceManager.GetString("CreateTableSentenceStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE tag_appearance (
        ///  id int primary key,
        ///  tag_definition_id int not null,
        ///  attribute_condition text,
        ///  target_project_id int not null,
        ///  target_user_id int not null,
        ///  appearance text not null,
        ///  priority int not null,
        ///  user_id int,
        ///  createtime timestamp,
        ///  description text
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableTagAppearanceStatement {
            get {
                return ResourceManager.GetString("CreateTableTagAppearanceStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE tag_definition (
        ///  id             int primary key,
        ///  tagset_id int not null,
        ///  type varchar(8) not null,
        ///  tag_name varchar(255) not null,
        ///  description text,
        ///  version_id int not null
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableTagDefinitionStatement {
            get {
                return ResourceManager.GetString("CreateTableTagDefinitionStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE tagset (
        ///  id             int primary key,
        ///  tagset_name varchar(255) not null
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableTagsetStatement {
            get {
                return ResourceManager.GetString("CreateTableTagsetStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE tagset_user (
        ///  user_id int not null,
        ///  tagset_id int not null,
        ///  user_privilege int not null
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableTagsetUserStatement {
            get {
                return ResourceManager.GetString("CreateTableTagsetUserStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE tagset_version (
        ///  version_id  int primary key,
        ///  tagset_id int not null,
        ///  version varchar(255) not null,
        ///  revision int not null,
        ///  current bool not null
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableTagsetVersionStatement {
            get {
                return ResourceManager.GetString("CreateTableTagsetVersionStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE user (
        ///  user_id  int primary key,
        ///  user_name varchar(255) not null,
        ///  user_password varchar(255),
        ///  user_privilege int,
        ///  comments text
        ///)
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableUserStatement {
            get {
                return ResourceManager.GetString("CreateTableUserStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE word (
        ///  id             int primary key,
        ///  sentence_id  int not null,
        ///  start_char int not null,
        ///  end_char     int not null,
        ///  lexeme_id     int not null,
        ///  bunsetsu_segment_id  bigint not null,
        ///  updated_at   timestamp,
        ///  position       int,
        ///  start_time  real,
        ///  end_time    real,
        ///  duration      real,
        ///  extra_chars  varchar(255) default &apos;&apos;,
        ///  project_id  int default 0,
        ///  head_info   int default 0
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableWordStatement {
            get {
                return ResourceManager.GetString("CreateTableWordStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE TABLE word_word (
        /// from_word int, 
        /// to_word int,
        /// comment  varchar(255) default &apos;&apos;
        ///) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateTableWordWordStatement {
            get {
                return ResourceManager.GetString("CreateTableWordWordStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS attribute_constraint に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableAttributeConstraintStatement {
            get {
                return ResourceManager.GetString("DropTableAttributeConstraintStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS bunsetsu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableBunsetsuStatement {
            get {
                return ResourceManager.GetString("DropTableBunsetsuStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS cform_ctype に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableCFormCTypeStatement {
            get {
                return ResourceManager.GetString("DropTableCFormCTypeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS cform に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableCFormStatement {
            get {
                return ResourceManager.GetString("DropTableCFormStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS corpus_attribute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableCorpusAttributeStatement {
            get {
                return ResourceManager.GetString("DropTableCorpusAttributeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS ctype に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableCTypeStatement {
            get {
                return ResourceManager.GetString("DropTableCTypeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS document_set_document に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableDocumentSetDocumentStatement {
            get {
                return ResourceManager.GetString("DropTableDocumentSetDocumentStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS document_set_project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableDocumentSetProjectStatement {
            get {
                return ResourceManager.GetString("DropTableDocumentSetProjectStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS document_set_project_user に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableDocumentSetProjectUserStatement {
            get {
                return ResourceManager.GetString("DropTableDocumentSetProjectUserStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS documentset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableDocumentsetStatement {
            get {
                return ResourceManager.GetString("DropTableDocumentsetStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS document_set_user に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableDocumentSetUserStatement {
            get {
                return ResourceManager.GetString("DropTableDocumentSetUserStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS document に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableDocumentStatement {
            get {
                return ResourceManager.GetString("DropTableDocumentStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS documenttag に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableDocumentTagStatement {
            get {
                return ResourceManager.GetString("DropTableDocumentTagStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS group_attribute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableGroupAttributeStatement {
            get {
                return ResourceManager.GetString("DropTableGroupAttributeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS group_constraint に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableGroupConstraintStatement {
            get {
                return ResourceManager.GetString("DropTableGroupConstraintStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS group_member に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableGroupMemberStatement {
            get {
                return ResourceManager.GetString("DropTableGroupMemberStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS group_ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableGroupStatement {
            get {
                return ResourceManager.GetString("DropTableGroupStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS lexeme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableLexemeStatement {
            get {
                return ResourceManager.GetString("DropTableLexemeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS link_attribute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableLinkAttributeStatement {
            get {
                return ResourceManager.GetString("DropTableLinkAttributeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS link_constraint に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableLinkConstraintStatement {
            get {
                return ResourceManager.GetString("DropTableLinkConstraintStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS link に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableLinkStatement {
            get {
                return ResourceManager.GetString("DropTableLinkStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS part_of_speech に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTablePartOfSpeechStatement {
            get {
                return ResourceManager.GetString("DropTablePartOfSpeechStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableProjectStatement {
            get {
                return ResourceManager.GetString("DropTableProjectStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS project_tagset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableProjectTagsetStatement {
            get {
                return ResourceManager.GetString("DropTableProjectTagsetStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS project_user に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableProjectUserStatement {
            get {
                return ResourceManager.GetString("DropTableProjectUserStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS segment_attribute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableSegmentAttributeStatement {
            get {
                return ResourceManager.GetString("DropTableSegmentAttributeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS segment_constraint に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableSegmentConstraintStatement {
            get {
                return ResourceManager.GetString("DropTableSegmentConstraintStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS segment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableSegmentStatement {
            get {
                return ResourceManager.GetString("DropTableSegmentStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS sentence_documenttag に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableSentenceDocumentTagStatement {
            get {
                return ResourceManager.GetString("DropTableSentenceDocumentTagStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS sentence に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableSentenceStatement {
            get {
                return ResourceManager.GetString("DropTableSentenceStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS tag_appearance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableTagAppearanceStatement {
            get {
                return ResourceManager.GetString("DropTableTagAppearanceStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS tag_definition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableTagDefinitionStatement {
            get {
                return ResourceManager.GetString("DropTableTagDefinitionStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS tagset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableTagsetStatement {
            get {
                return ResourceManager.GetString("DropTableTagsetStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS tagset_user に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableTagsetUserStatement {
            get {
                return ResourceManager.GetString("DropTableTagsetUserStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS tagset_version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableTagsetVersionStatement {
            get {
                return ResourceManager.GetString("DropTableTagsetVersionStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS user に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableUserStatement {
            get {
                return ResourceManager.GetString("DropTableUserStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS word に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableWordStatement {
            get {
                return ResourceManager.GetString("DropTableWordStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE IF EXISTS word_word に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableWordWordStatement {
            get {
                return ResourceManager.GetString("DropTableWordWordStatement", resourceCulture);
            }
        }
    }
}
