//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaKi.Text2Corpus.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChaKi.Text2Corpus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon ChaMame {
            get {
                object obj = ResourceManager.GetObject("ChaMame", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   File... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ⚻ Hide Detailed Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HideDetailedLog {
            get {
                return ResourceManager.GetString("HideDetailedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutputLabel {
            get {
                return ResourceManager.GetString("OutputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input file or folder does not exist: {0}. Please specify an existing file or folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S001 {
            get {
                return ResourceManager.GetString("S001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input folder &apos;{0}&apos; contains no text file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S002 {
            get {
                return ResourceManager.GetString("S002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About to delete {0} files in the output folder.  Are you sure to continue?\n\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S003 {
            get {
                return ResourceManager.GetString("S003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   --------------- Files to be overwritten --------------\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S004 {
            get {
                return ResourceManager.GetString("S004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not determine character code Mecab uses. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S005 {
            get {
                return ResourceManager.GetString("S005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conversion completed.\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S006 {
            get {
                return ResourceManager.GetString("S006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line Separation,  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S007 {
            get {
                return ResourceManager.GetString("S007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MeCab Analysis (CharacterCode:{0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S008 {
            get {
                return ResourceManager.GetString("S008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   , and CaboCha Analysis are performed. \n\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S009 {
            get {
                return ResourceManager.GetString("S009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   are performed.\n\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S010 {
            get {
                return ResourceManager.GetString("S010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S011 {
            get {
                return ResourceManager.GetString("S011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line Separation... (File {0}/{1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S012 {
            get {
                return ResourceManager.GetString("S012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MeCab Processing ... (File {0}/{1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S013 {
            get {
                return ResourceManager.GetString("S013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CaboCha Processing ... (File {0}/{1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S014 {
            get {
                return ResourceManager.GetString("S014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CreateCorpus Processing ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S015 {
            get {
                return ResourceManager.GetString("S015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ==== Output Preview (CharCode: utf-8) ====\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S016 {
            get {
                return ResourceManager.GetString("S016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cabocha not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S017 {
            get {
                return ResourceManager.GetString("S017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CreateCorpus not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S018 {
            get {
                return ResourceManager.GetString("S018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mecab not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S019 {
            get {
                return ResourceManager.GetString("S019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S020 {
            get {
                return ResourceManager.GetString("S020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not locate Mecab Model path for {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S021 {
            get {
                return ResourceManager.GetString("S021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not locate Cabocha Model path for {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S022 {
            get {
                return ResourceManager.GetString("S022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ⚺ Show Detailed Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowDetailedLog {
            get {
                return ResourceManager.GetString("ShowDetailedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowFolder {
            get {
                return ResourceManager.GetString("ShowFolder", resourceCulture);
            }
        }
    }
}
